spring.application.name=app

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/hackhub}
spring.datasource.username=${DB_USERNAME:hackhub}
spring.datasource.password=${DB_PASSWORD:hackhub}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true