apiVersion: v1
kind: Secret
metadata:
  name: hackhub-secrets
  namespace: hackhub
type: Opaque
stringData:
  DB_PASSWORD: cambia-questa-password
  JWT_SECRET: cambia-questo-secret-minimo-64-caratteri-stringa-casuale-sicura!!xx
